<!DOCTYPE html>
<html>
<head>
    <title>This notification is generated by Laravel </title>
</head>
<body>
    <p>{{ $commentdata['user_name'] }} has commented on your post <b>{{ $commentdata['post_name'] }}</b></p>

    <hr>
    <p>{{ $commentdata['comment'] }}</p>

</body>
</html>
